services:
  web:
    build:
      context: ./app
    image: oddball-svc:local
    ports:
      - "8080:8080"
    environment:
      FLASK_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/').read()\""]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

